// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuyncvgnbgjbnrqlzvqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1eW5jdmduYmdqYm5ycWx6dnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDg2NDcsImV4cCI6MjA2MjcyNDY0N30.qQ5iAskJLfvsfY8jhqTfbfMfnuwmoCpzO1Ses0u2G5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);